# application-prod.yml
server:
  port: ${SERVER_PORT:8084}
  servlet:
    context-path: /api/v1

spring:
  application:
    name: audit-service

  datasource:
    url: jdbc:mysql://${DB_HOST:audit-mysql.kopingenieria.com}:${DB_PORT:3306}/${DB_NAME:audit_db}?useSSL=true&serverTimezone=America/Lima&requireSSL=true&verifyServerCertificate=true&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:audit_user}
    password: ${DB_PASSWORD:K0p1ng3n13r14@2024}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: AuditHikariCP-Prod
      minimum-idle: 10
      maximum-pool-size: 30
      idle-timeout: 300000
      max-lifetime: 900000
      connection-timeout: 20000
      connection-test-query: SELECT 1 FROM DUAL

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
        generate_statistics: false
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          time_zone: America/Lima

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
    export:
      prometheus:
        enabled: true
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true

logging:
  level:
    root: WARN
    org.kopingenieria.audit: INFO
    org.springframework: WARN
    org.springframework.web: WARN
    org.springframework.security: WARN
    org.springframework.data: WARN
    org.hibernate: WARN
    com.zaxxer.hikari: WARN
  file:
    name: /var/log/audit-service/application.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30
      total-size-cap: 3GB
      clean-history-on-start: false

audit:
  retention:
    days: 90
  async:
    core-pool-size: 4
    max-pool-size: 10
    queue-capacity: 1000