spring:
  application:
    name: audit
    version: 1.0.0
    title: Audit Service

  profiles:
    active: dev

  datasource:
    url: jdbc:mysql://localhost:3306/audit_db?useSSL=false&serverTimezone=America/Lima
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: AuditHikariCP
      minimum-idle: 5
      maximum-pool-size: 10

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          time_zone: America/Lima

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

server:
  port: ${SERVER_PORT:8084}
  servlet:
    context-path: /api/v1

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true

logging:
  level:
    root: INFO
    org.kopingenieria.audit: DEBUG
    org.springframework: INFO

audit:
  retention:
    days: 90
  async:
    core-pool-size: 2
    max-pool-size: 5
    queue-capacity: 500

