spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://${DB_HOST:audit-mysql.kopingenieria.com}:${DB_PORT:3306}/${DB_NAME:audit_db}?useSSL=true&serverTimezone=America/Lima&requireSSL=true&verifyServerCertificate=true&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:audit_user}
    password: ${DB_PASSWORD:K0p1ng3n13r14@2024}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: AuditHikariCP-Prod
      minimum-idle: 10
      maximum-pool-size: 30
      idle-timeout: 300000
      max-lifetime: 900000
      connection-timeout: 20000
      connection-test-query: SELECT 1 FROM DUAL
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        generate_statistics: false
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          time_zone: America/Mexico_City

server:
  ssl:
    enabled: true
    key-store: ${SSL_KEYSTORE_PATH}
    key-store-password: ${SSL_KEYSTORE_PASSWORD}
    key-store-type: PKCS12
    key-alias: ${SSL_KEY_ALIAS}

logging:
  level:
    root: WARN
    org.kopingenieria.audit: INFO
    org.springframework: WARN
    org.springframework.web: WARN
    org.springframework.security: WARN
    org.springframework.data: WARN
    org.hibernate: WARN
    com.zaxxer.hikari: WARN
  file:
    name: /var/log/audit-service/application.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30
      total-size-cap: 3GB
      clean-history-on-start: false

management:
  metrics:
    tags:
      application: ${spring.application.name}
    export:
      prometheus:
        enabled: true
  endpoint:
    prometheus:
      enabled: true

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: Authorization,Content-Type
  exposed-headers: X-Total-Count
  allow-credentials: true
  max-age: 3600

security:
  jwt:
    secret: ${JWT_SECRET}
    expiration: 86400000
    refresh-token:
      expiration: 604800000

monitoring:
  newrelic:
    enabled: true
    license-key: ${NEW_RELIC_LICENSE_KEY}
  datadog:
    enabled: true
    api-key: ${DATADOG_API_KEY}

cdn:
  enabled: true
  base-url: ${CDN_BASE_URL}
  access-key: ${CDN_ACCESS_KEY}
  secret-key: ${CDN_SECRET_KEY}

redis:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}
  password: ${REDIS_PASSWORD}
  timeout: 2000
  database: 0