spring:
  application:
    name: audit
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

# Configuración del servidor
server:
  port: ${SERVER_PORT:8084}
  tomcat:
    max-threads: 200
    min-spare-threads: 10
    max-connections: 10000
    connection-timeout: 5000
    accesslog:
      enabled: true
      directory: logs
      prefix: access_log
      suffix: .log
      pattern: common
  compression:
    enabled: true
    mime-types:
      - application/json
      - application/xml
      - text/html
      - text/xml
      - text/plain
    min-response-size: 2048
  http2:
    enabled: true
  servlet:
    context-path: /api/v1
    session:
      timeout: 30m

audit:
  async-enabled: true
  thread-pool:
    core-size: 2
    max-size: 4
    queue-capacity: 100
    keep-alive-seconds: 60
    thread-name-prefix: "Audit-"
    allow-core-thread-timeout: true
    wait-for-tasks-to-complete-on-shutdown: true
    await-termination-seconds: 60
  retention:
    days: 90
    enabled: true
    cleanup-cron: "0 0 1 * * ?"
  cache:
    enabled: true
    cache-name: "auditEvents"
    time-to-live-seconds: 3600
    max-elements: 1000

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - metrics
          - loggers
          - info
          - prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
    export:
      prometheus:
        enabled: true
  info:
    git:
      mode: full

feign:
  client:
    config:
      logging-service:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
        defaultRequestHeaders:
          X-API-Key: ${LOGGING_API_KEY}

resilience4j:
  retry:
    instances:
      logging-service:
        maxAttempts: 3
        waitDuration: 1s
        enableExponentialBackoff: true
  circuitbreaker:
    instances:
      logging-service:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 30s

logging:
  central:
    enabled: true
    service:
      url: ${LOGGING_SERVICE_URL:http://logging-service:8089}
      api-key: ${LOGGING_API_KEY}
    async:
      enabled: true
      batch-size: 100
      queue-size: 512
      flush-interval: 5000
    fields:
      application: ${spring.application.name}
      environment: ${spring.profiles.active}
      additional:
        - userId
        - sessionId
        - traceId
        - requestId
    patterns:
      include:
        - "org.kopingenieria.audit.*"
      exclude:
        - "org.springframework.*"
        - "org.hibernate.*"
    format:
      timestamp-pattern: "yyyy-MM-dd'T'HH:mm:ss.SSSZ"
      mask-sensitive-data: true
      include-stacktrace: true
  file:
    path: ${LOG_BASE_DIR:/var/log/rochling/audit-service}
  level:
    root: ${LOG_LEVEL:INFO}
    org.kopingenieria.audit: ${LOG_LEVEL:INFO}
    org.springframework: WARN

info:
  app:
    name: ${APP_NAME:audit}
    version: ${APP_VERSION:1.0.0}
    description: ${APP_DESCRIPTION:Audit Service}
  java:
    version: ${java.version}
  spring:
    profiles:
      active: ${spring.profiles.active:dev}
