opcua:
  name: ${OPCUA_NAME:OPC UA Configuration}
  description: ${OPCUA_DESCRIPTION:Configuración principal del cliente OPC UA}
  enabled: ${OPCUA_ENABLED:true}
  version: ${OPCUA_VERSION:1}

  connection:
    endpointUrl: ${OPCUA_ENDPOINT_URL:opc.tcp://localhost:4840}
    applicationName: ${OPCUA_APP_NAME:KopIngenieria OPC UA Client}
    applicationUri: ${OPCUA_APP_URI:urn:kopingenieria:client}
    productUri: ${OPCUA_PRODUCT_URI:urn:kopingenieria:client:product}
    requestTimeout: ${OPCUA_REQUEST_TIMEOUT:5000}
    channelLifetime: ${OPCUA_CHANNEL_LIFETIME:300000}

  authentication:
    username: ${OPCUA_AUTH_USERNAME:}
    password: ${OPCUA_AUTH_PASSWORD:}
    securityPolicy: ${OPCUA_SECURITY_POLICY:Basic256Sha256}
    securityMode: ${OPCUA_SECURITY_MODE:SignAndEncrypt}
    certificatePath: ${OPCUA_CERT_PATH:certificates/client.der}
    privateKeyPath: ${OPCUA_KEY_PATH:certificates/client.pem}
    anonymous: ${OPCUA_AUTH_ANONYMOUS:false}

  encryption:
    securityPolicy: ${OPCUA_ENCRYPTION_SECURITY_POLICY:Basic256Sha256}
    messageMode: ${OPCUA_ENCRYPTION_MESSAGE_MODE:SignAndEncrypt}
    algorithm: ${OPCUA_ENCRYPTION_ALGORITHM:AES}
    keySize: ${OPCUA_ENCRYPTION_KEY_SIZE:256}
    certificateType: ${OPCUA_ENCRYPTION_CERT_TYPE:DER}
    validateCertificate: ${OPCUA_ENCRYPTION_VALIDATE_CERT:true}

  session:
    sessionName: ${OPCUA_SESSION_NAME:KopIngenieria Session}
    sessionTimeout: ${OPCUA_SESSION_TIMEOUT:60000}
    maxResponseMessageSize: ${OPCUA_SESSION_MAX_RESPONSE_SIZE:65535}
    maxRequestMessageSize: ${OPCUA_SESSION_MAX_REQUEST_SIZE:65535}
    publishingEnabled: ${OPCUA_SESSION_PUBLISHING_ENABLED:true}

  subscriptions:
    - name: ${OPCUA_SUB_NAME:Subscription1}
      publishingInterval: ${OPCUA_SUB_PUBLISHING_INTERVAL:1000.0}
      lifetimeCount: ${OPCUA_SUB_LIFETIME_COUNT:1000}
      maxKeepAliveCount: ${OPCUA_SUB_MAX_KEEPALIVE_COUNT:500}
      maxNotificationsPerPublish: ${OPCUA_SUB_MAX_NOTIFICATIONS:1000}
      priority: ${OPCUA_SUB_PRIORITY:1}
      publishingEnabled: ${OPCUA_SUB_PUBLISHING_ENABLED:true}

  monitoring-events:
    - nodeId: ${OPCUA_MONITOR_NODE_ID:ns=2;s=Device1.Tag1}
      browsePath: ${OPCUA_MONITOR_BROWSE_PATH:Channel1.Device1.Tag1}
      displayName: ${OPCUA_MONITOR_DISPLAY_NAME:Temperature Sensor 1}
      samplingInterval: ${OPCUA_MONITOR_SAMPLING_INTERVAL:1000.0}
      queueSize: ${OPCUA_MONITOR_QUEUE_SIZE:1}
      discardOldest: ${OPCUA_MONITOR_DISCARD_OLDEST:true}
      monitoringMode: ${OPCUA_MONITOR_MODE:Reporting}
      dataType: ${OPCUA_MONITOR_DATA_TYPE:Double}
      triggerType: ${OPCUA_MONITOR_TRIGGER_TYPE:StatusValue}

  industrial-configuration:
    industrialZone: ${OPCUA_INDUSTRIAL_ZONE:ZONE_001}
    equipmentId: ${OPCUA_EQUIPMENT_ID:EQ_001}
    areaId: ${OPCUA_AREA_ID:AREA_001}
    processId: ${OPCUA_PROCESS_ID:PROC_001}
    operatorName: ${OPCUA_OPERATOR_NAME:DEFAULT_OPERATOR}
    operatorId: ${OPCUA_OPERATOR_ID:12345}