logging:
  service:
    name: logging
    version: 1.0.0
    elasticsearch:
      hosts: ${ELASTICSEARCH_HOSTS:localhost:9200}
      index-prefix: logs
    bulk-processing:
      batch-size: 1000
      flush-interval: 5000
    retention:
      days: 30
    masking:
      enabled: true
      patterns:
        - password
        - creditCard
        - ssn