spring:
  application:
    name: ms-logging
    description: Microservicio de Logging
    version: 1.0.0
  main:
    banner-mode: console
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: HikariCP
      auto-commit: false
      connection-timeout: 20000
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 300000
      max-lifetime: 1200000
  jpa:
    open-in-view: false
    properties:
      hibernate:
        jdbc.batch_size: 50
        order_inserts: true
        order_updates: true
        jdbc.time_zone: UTC
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=3600s
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

app:
  elasticsearch:
    index-prefix: kop-logs
    hosts:
      - http://localhost:9200
    username: ${ELASTIC_USERNAME:elastic}
    password: ${ELASTIC_PASSWORD:changeme}
    bulk-size: 1000
    flush-interval: 5
    ssl-enabled: false
    number-of-shards: 1
    number-of-replicas: 1
    retry:
      max-attempts: 3
      initial-interval: 1000
      multiplier: 2.0
      max-interval: 10000
  file-config:
    base-path: /var/log/kopingenieria
    log-pattern: "%d{ISO8601} [%thread] %-5level %logger{36} - %msg%n"
    max-file-size: 10
    max-history: 7
    compress-backups: true
    name-pattern: "%d{yyyy-MM-dd}.log"
    root-level: INFO
    application-level: INFO
  security:
    enable-audit: true
    audit-log-path: /var/log/kopingenieria/audit
    sensitive-fields:
      - password
      - token
      - creditCard
    mask-sensitive-data: true
  performance:
    enable-metrics: true
    buffer-size: 8192
    queue-size: 512
    async-logging: true

server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 2048
  http2:
    enabled: true
  servlet:
    context-path: /api
    session:
      timeout: 30m

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,loggers,info,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
    export:
      prometheus:
        enabled: true
  info:
    git:
      mode: full

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 100
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10000
        permitted-number-of-calls-in-half-open-state: 10
  retry:
    configs:
      default:
        max-attempts: 3
        wait-duration: 1000
  ratelimiter:
    configs:
      default:
        limit-for-period: 100
        limit-refresh-period: 1s
        timeout-duration: 0s

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
  compression:
    request:
      enabled: true
    response:
      enabled: true