spring:
  config:
    activate:
      on-profile: ${SPRING_PROFILES_ACTIVE}
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  cache:
    type: none

app:
  elasticsearch:
    index-prefix: ${ELASTICSEARCH_INDEX_PREFIX}-${SPRING_PROFILES_ACTIVE}
    hosts: ${ELASTICSEARCH_HOSTS}
    bulk-size: 500
    flush-interval: 1
    ssl-enabled: false
    number-of-shards: ${ELASTICSEARCH_SHARDS}
    number-of-replicas: ${ELASTICSEARCH_REPLICAS}
  file-config:
    base-path: ${LOG_BASE_DIR}
    max-file-size: ${LOG_MAX_FILE_SIZE}
    max-history: ${LOG_MAX_HISTORY}
    compress-backups: false
    root-level: ${LOG_LEVEL}
    application-level: TRACE
  security:
    enable-audit: false
    mask-sensitive-data: false
  performance:
    enable-metrics: true
    buffer-size: 4096
    queue-size: 256
    async-logging: false

logging:
  level:
    root: ${LOG_LEVEL}
    ${SERVICE_GROUP}: TRACE
    org.springframework: DEBUG

cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "*"
  allow-credentials: true
  max-age: 3600