spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kopdb_dev
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  cache:
    type: none

app:
  elasticsearch:
    index-prefix: kop-logs-dev
    hosts:
      - http://localhost:9200
    bulk-size: 500
    flush-interval: 1
    ssl-enabled: false
    number-of-shards: 1
    number-of-replicas: 0
  file-config:
    base-path: /var/log/kopingenieria/dev
    max-file-size: 10
    max-history: 3
    compress-backups: false
    root-level: DEBUG
    application-level: TRACE
  security:
    enable-audit: false
    mask-sensitive-data: false
  performance:
    enable-metrics: true
    buffer-size: 4096
    queue-size: 256
    async-logging: false

server:
  port: 8080
  error:
    include-stacktrace: always
    include-message: always

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: DEBUG
    org.kopingenieria: TRACE
    org.springframework: DEBUG
    org.hibernate: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE

cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "*"
  allow-credentials: true
  max-age: 3600